### ISSUE TITLE
GetCurrentTHreadStackLimits

### ISSUE THREAD

**Issue by quetzalsly** [jdpatdiscord/ExceptionHandler#5]
GetCurrentTHreadStackLimits seems to have an issue on windows 7, it does not work.
Any way to use something else or a conditional compilation flag?

**Comment by jdpatdiscord** [comment]
Hi Quetz,

Thanks for bringing this to my attention. That code snippet that contains `GetCurrentThreadStackLimits` is not used and probably won't be. You may delete it. I will remove it in a commit soon.

**Comment by jdpatdiscord** [comment]
The code snippet has been removed. Let me know if you run into any other issues.
